const About = () => {
    
    return (
        <div>
            <h1>About page</h1>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequatur ad ratione porro dolore a neque quis nemo eum quasi explicabo, consequuntur fugit corporis amet quae magni tempora quia. Ducimus delectus facere reiciendis vitae eligendi expedita aspernatur provident hic deserunt! Iusto odit molestias corrupti hic quae illum, accusamus velit quos. Aperiam, saepe. Nihil, perspiciatis dignissimos? Ipsa beatae ratione molestiae laborum explicabo itaque numquam, aspernatur fugiat consequatur nihil officia omnis similique incidunt repudiandae non odio recusandae magnam. Voluptatem, repudiandae veritatis sapiente laudantium vel similique exercitationem sunt doloribus illum temporibus culpa fuga nihil nemo eum quaerat ex sed odio necessitatibus a corporis error quis. Cum consequatur nihil blanditiis, quisquam, quibusdam asperiores reiciendis architecto fugit consequuntur provident quasi harum exercitationem labore magnam voluptates totam iusto officia fugiat voluptatibus numquam assumenda itaque dolores aliquid alias. Quae veniam dolor vitae fuga repellendus porro nesciunt labore dignissimos voluptatum repellat dolorem, ut adipisci sit aliquid possimus eos earum deleniti quisquam at necessitatibus! Nihil consequuntur maxime tenetur fugit et, libero ipsa. Voluptas at facere maiores obcaecati, praesentium ipsam dolorum voluptate rerum, beatae corporis voluptatum totam! Maxime quam sit necessitatibus neque? Expedita dolores tempore distinctio aliquam libero quas? Repellat atque tempora odit quaerat! Vel excepturi voluptates, doloribus quos earum facilis?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum nostrum itaque quam ullam inventore voluptate voluptas architecto commodi. Excepturi odit dolorum, obcaecati enim hic beatae iure labore nemo, dolores facere sapiente modi veritatis praesentium voluptatum, delectus itaque nihil minus officia? Quia omnis eaque doloribus nesciunt est beatae numquam, dolore explicabo totam commodi doloremque maiores rem fugiat quibusdam nulla maxime consectetur. Aspernatur accusamus nulla, quae impedit natus ab excepturi in, repellat perferendis voluptatem dolorum a officia mollitia quos voluptates? Ducimus, veniam suscipit! Aliquid optio perspiciatis obcaecati autem eum rerum sit. Illo nemo maiores ex fuga exercitationem autem dolores facere doloribus rem quos, consequuntur aspernatur cupiditate inventore quidem asperiores alias veritatis vitae incidunt accusantium culpa magnam. Molestias vitae aperiam dolores modi itaque quisquam neque impedit expedita, optio quae ex ratione laudantium harum cupiditate dignissimos assumenda. Odio omnis, saepe officia eum quibusdam maxime aliquid vel doloremque! Nesciunt reprehenderit quo eveniet ratione nostrum quos, id aperiam ad perspiciatis porro accusamus fugit veniam? Quis odio ratione eaque ipsa, numquam dolorem? Natus voluptas veniam placeat quaerat mollitia eius suscipit, expedita eum consequuntur. Dolorem, illum. Minima laudantium consequuntur impedit assumenda, tenetur eius sequi repudiandae distinctio quasi similique excepturi modi ut repellat. Fuga dolores distinctio rerum iure voluptates.</p>
        </div>
    )
}

export default About;